layout:
    actions:
        - '@setBlockTheme':
            themes: 'OroGoogleTagManagerBundle:layouts:blank/oro_frontend_root/product_list_gtm.html.twig'
        - '@add':
            id: featured_products_list_gtm
            parentId: featured_products_container
            blockType: block
            options:
                visible: '=data["oro_google_tag_manager_settings"].isReady()'
        - '@add':
            id: new_arrivals_list_gtm
            parentId: new_arrival_products_container
            blockType: block
            options:
                visible: '=data["oro_google_tag_manager_settings"].isReady()'
        - '@add':
            id: top_selling_list_gtm
            parentId: top_selling_items_container
            blockType: block
            options:
                visible: '=data["oro_google_tag_manager_settings"].isReady()'
