config:
    paths:
        'orogoogletagmanager/js/app/components/data-layer-manager-component': 'bundles/orogoogletagmanager/js/app/components/data-layer-manager-component.js'
        'orogoogletagmanager/js/app/components/product-model-expose-component': 'bundles/orogoogletagmanager/js/app/components/product-model-expose-component.js'
        'orogoogletagmanager/js/app/components/base-embedded-list-gtm-component': 'bundles/orogoogletagmanager/js/app/components/base-embedded-list-gtm-component.js'
        'orogoogletagmanager/js/app/components/products-embedded-list-gtm-component': 'bundles/orogoogletagmanager/js/app/components/products-embedded-list-gtm-component.js'
        'orogoogletagmanager/js/app/components/home-page-slider-gtm-component': 'bundles/orogoogletagmanager/js/app/components/home-page-slider-gtm-component.js'
        'orogoogletagmanager/js/app/handlers/checkout-handler': 'bundles/orogoogletagmanager/js/app/handlers/checkout-handler.js'
