layout:
    actions:
        - '@setOption':
            id: google_tag_manager_product_grid
            optionName: attr.data-page-component-options.relatedSiblingComponents.productsDatagridComponent
            optionValue: 'frontend-product-search-grid'

        - '@setOption':
            id: google_tag_manager_product_grid
            optionName: vars.productsDatagridGtmListName
            optionValue: 'product-index'
