services:
    oro_google_tag_manager.data_layer.collector.page_variables:
        class: 'Oro\Bundle\GoogleTagManagerBundle\DataLayer\Collector\PageVariablesCollector'
        public: false
        arguments:
            - '@oro_google_tag_manager.provider.page_type'
            - '@oro_locale.helper.localization'
        tags:
            - { name: oro_google_tag_manager.data_layer.collector }

    oro_google_tag_manager.data_layer.collector.user_detail:
        class: 'Oro\Bundle\GoogleTagManagerBundle\DataLayer\Collector\UserDetailCollector'
        public: false
        arguments:
            - '@oro_security.token_accessor'
        tags:
            - { name: oro_google_tag_manager.data_layer.collector }

    oro_google_tag_manager.data_layer.collector.catalog_detail:
        class: 'Oro\Bundle\GoogleTagManagerBundle\DataLayer\Collector\CatalogDetailCollector'
        public: false
        arguments:
            - '@oro_web_catalog.layout.data_provider.breadcrumb_data'
        tags:
            - { name: oro_google_tag_manager.data_layer.collector }
