services:
    oro_google_tag_manager.data_layer.manager:
        class: 'Oro\Bundle\GoogleTagManagerBundle\DataLayer\DataLayerManager'
        public: false
        arguments:
            - '@session'
            - ~ # collectors

    oro_google_tag_manager.provider.google_tag_manager_settings:
        class: 'Oro\Bundle\GoogleTagManagerBundle\Provider\GoogleTagManagerSettingsProvider'
        public: false
        arguments:
            - '@doctrine'
            - '@oro_config.manager'

    oro_google_tag_manager.provider.page_type:
        class: 'Oro\Bundle\GoogleTagManagerBundle\Provider\PageTypeProvider'
        public: false
        arguments:
            - ~ # page type guessers

    oro_google_tag_manager.page_type_guesser.by_request_route:
        class: 'Oro\Bundle\GoogleTagManagerBundle\Provider\PageType\PageTypeGuesserByRequestRoute'
        public: false
        arguments:
            - '@request_stack'
            -
                oro_frontend_root': 'home'
                oro_product_frontend_product_index: 'category'
                oro_product_frontend_product_view: 'product'
                oro_shopping_list_frontend_view: 'basket'
                oro_sale_quote_frontend_view: 'basket'
                oro_checkout_frontend_checkout: 'checkout'
                oro_product_frontend_product_search: 'search'
        tags:
            - { name: oro_google_tag_manager.page_type_guesser, priority: 100 }

    oro_google_tag_manager.provider.product_detail_provider:
        class: 'Oro\Bundle\GoogleTagManagerBundle\Provider\ProductDetailProvider'
        public: false
        arguments:
            - '@oro_locale.provider.config_default_localization'
            - '@oro_entity.doctrine_helper'

    oro_google_tag_manager.event_listener.website_search_index:
        class: 'Oro\Bundle\GoogleTagManagerBundle\EventListener\WebsiteSearchIndexerListener'
        public: false
        arguments:
            - '@oro_website.provider.website_localization'
            - '@oro_website_search.manager.website_context_manager'
            - '@oro_google_tag_manager.provider.product_detail_provider'
        tags:
            - { name: kernel.event_listener, event: oro_website_search.event.index_entity.product, method: onWebsiteSearchIndex }

    oro_google_tag_manager.event_listener.frontend_product_datagrid:
        class: 'Oro\Bundle\GoogleTagManagerBundle\EventListener\FrontendProductDatagridListener'
        public: false
        arguments:
            - '@oro_google_tag_manager.provider.google_tag_manager_settings'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.pre.frontend-product-search-grid, method: onPreBuild }
            - { name: kernel.event_listener, event: oro_datagrid.search_datasource.result.after.frontend-product-search-grid, method: onResultAfter }
