services:
    oro_google_tag_manager.twig.product_detail_extension:
        class: 'Oro\Bundle\GoogleTagManagerBundle\Twig\ProductDetailExtension'
        public: false
        arguments:
            - '@Psr\Container\ContainerInterface'
        tags:
            - { name: twig.extension }
            - { name: container.service_subscriber }
