services:
    oro_google_tag_manager.twig.product_detail_extension:
        class: Oro\Bundle\GoogleTagManagerBundle\Twig\ProductDetailExtension
        arguments:
            - '@oro_platform.twig.service_locator'
        tags:
            - { name: twig.extension }
