layout:
    actions:
        - '@setOption':
            id: google_tag_manager_product_grid
            optionName: attr.data-page-component-options.relatedSiblingComponents.productsDatagridComponent
            optionValue: '=context["product_grid_name"]'

        - '@setOption':
            id: google_tag_manager_product_grid
            optionName: vars.productsDatagridGtmListName
            optionValue: 'previously-purchased'
